# Generated by Django 4.1.9 on 2023-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Enter your birthdate', null=True, verbose_name='Date of Birth'),
        ),
    ]
