# Generated by Django 4.1.9 on 2023-06-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joining_data',
            new_name='joining_date',
        ),
    ]
